PHP 8: Fixed archive import from Amazon S3
akeeba/kickstart pull request #29
Opened 2021-11-05 14:59 UTC by tampe125

Close #27

2021-11-05 15:19 UTC, nikosdion requested changes

2021-11-05 15:19 UTC, nikosdion commented on source/s3/s3.connector.php
> +                    $response->error->getCode(), $response->error->getMessage(), print_r($response->body, true))
Since we're doing this, can you please put $bucket and $uri as `sprintf` variables?

2021-11-05 15:19 UTC, nikosdion commented on source/urlimport/feature.urlimport.php
> +        if (!$size)
I'd prefer doing it differently:
```php
$size = (int)($size ?: 0)
```
The Elvis operator is available since PHP 5.3. The above is equivalent to writing:
```php
$size = (int)(empty($size) ? 0 : $size);
```

2021-11-05 15:19 UTC, nikosdion commented on source/s3/s3.connector.php
> +                    $response->error->getCode(), $response->error->getMessage(), print_r($response->body, true))
BTW, can you also make a PR to https://github.com/akeeba/s3/blob/development/src/Connector.php so the changes sync to all our software?

2021-11-23 09:28 UTC, tampe125 commented on source/urlimport/feature.urlimport.php
> +        if (!$size)
mhm... no, that's different. The problem is that $size is 0 and then the following operation raises a fatal error. So if we have anything that will be cast to 0, we have to return early instead of going with the log/pow steps.

2021-11-23 09:29 UTC, merged